CREATE TABLE users(id SERIAL PRIMARY KEY, name VARCHAR(150), password VARCHAR(150));
CREATE TABLE messages(id SERIAL PRIMARY KEY, sender VARCHAR(150), text VARCHAR(100), time TIMESTAMP);
CREATE TABLE chatrooms(id SERIAL PRIMARY KEY, chatname VARCHAR(150), creator VARCHAR(150));